sudo: required
dist: trusty

branches:
  only:
    - master

compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh CC="gcc-5"

language: c

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - check
            - clang-3.8
            - clang-format-3.8
            - gcc-5
            - libblkid-dev
            - lcov
            - llvm-3.8
            - valgrind


before_install:
  - gem install coveralls-lcov

script:
    - lcov --version | grep "1.10"
    - export CC="gcc-5"
    - ./configure --enable-coverage && make && make check && make distcheck && make check-valgrind
    - clang-format-3.8 -i $(find . -name '*.[ch]') && git diff --exit-code


after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - coveralls-lcov coverage.info
